# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  orgName: prlmushr
  repoName: mushr
  dockerDir: ./dockerfiles

env:
  DOCKER_PASSWORD: $(dockerPassword)
  DOCKER_USERNAME: $(dockerID)

steps:
- name: BuildXenial
  displayName: Build docker image for Xenial
  script: |
    set -ex
    docker build -f $(dockerDir)/xenial.dockerfile -t $(orgName)/$(repoName):xenial $(dockerDir)
    echo $DOCKER_PASSWORD
    echo $DOCKER_USERNAME
    cat $DOCKER_PASSWORD | docker login -u $(dockerID) --password-stdin
    docker push $(orgName)/$(repoName):$(dockerTag)
- name: BuildBionic
  displayName: Build docker image for Bionic
  script: |
    set -ex
    docker build -f $(dockerDir)/bionic.dockerfile -t $(orgName)/$(repoName):bionic $(dockerDir)
    cat $DOCKER_PASSWORD | docker login -u $(dockerID) --password-stdin
    docker push $(orgName)/$(repoName):$(dockerTag)
