# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  orgName: prlmushr
  repoName: mushr
  dockerDir: ./dockerfiles

jobs:
- job: BuildDockerFiles
  steps:
  - bash: |
      set -ex
      docker build -f $(dockerDir)/xenial.dockerfile -t $(orgName)/$(repoName):xenial $(dockerDir)
      docker build -f $(dockerDir)/bionic.dockerfile -t $(orgName)/$(repoName):bionic $(dockerDir)

      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      docker push $(orgName)/$(repoName):xenial
      docker push $(orgName)/$(repoName):bionic
    env:
      DOCKER_PASSWORD: $(dockerPassword)
      DOCKER_USERNAME: $(dockerID)
