# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  orgName: prlmushr
  repoName: mushr
  dockerDir: ./dockerfiles

jobs:
- job: BuildDockerFiles
  name: Build Docker Files
  steps:
  - bash: |
      set -ex
      echo "Docker password: $DOCKER_PASSWORD, Docker username: $(DOCKER_USERNAME)"
      exit 1;
      docker build -f $(dockerDir)/xenial.dockerfile -t $(orgName)/$(repoName):xenial $(dockerDir)
      docker build -f $(dockerDir)/bionic.dockerfile -t $(orgName)/$(repoName):bionic $(dockerDir)

      cat $DOCKER_PASSWORD | docker login -u $(dockerID) -p $DOCKER_PASSOWORD

      docker push $(orgName)/$(repoName):xenial
      docker push $(orgName)/$(repoName):bionic
    env:
      DOCKER_PASSWORD: $(dockerPassword)
      DOCKER_USERNAME: $(dockerID)
