# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  orgName: prlmushr
  repoName: mushr
  dockerDir: ./dockerfiles

jobs:
- job: BuildDockerFiles
  steps:
  - task: DownloadSecureFile@1
    name: dockerpass
    displayName: "Download docker password"
    inputs:
      secureFile: 'dockerpass'
  - bash: |
      set -ex
      # docker build -f $(dockerDir)/xenial.dockerfile -t $(orgName)/$(repoName):xenial $(dockerDir)
      docker build -f $(dockerDir)/bionic.dockerfile -t $(orgName)/$(repoName):bionic $(dockerDir)

      cat $(dockerpass.secureFilePath) | docker login -u $DOCKER_USERNAME --password-stdin

      # docker push $(orgName)/$(repoName):xenial
      docker push $(orgName)/$(repoName):bionic
    env:
      DOCKER_USERNAME: $(dockerID)
