# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  orgName: prlmushr
  repoName: mushr
  dockerTag: xenial # also serves as tag
  dockerDir: ./dockerfiles

steps:
- script: |
    set -ex
    docker build -f $(dockerDir)/$(dockerTag).dockerfile -t $(orgName)/$(repoName):$(dockerTag) $(dockerDir)
    docker login -u $(dockerID) -p $(dockerPassword)
    docker push $(orgName)/$(repoName):$(dockerTag)
